In [13]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)
arr1.size

# find the data type 
print(arr1.dtype)
print(type(arr1))

[1 2 3 4 5]
int64
<class 'numpy.ndarray'>


In [20]:
# Multi dimensional array
arr2 = np.array([(1,2,3,4),(1,2,3.5,5)],dtype=complex)
print(arr2)
print(arr2.dtype)

[[1. +0.j 2. +0.j 3. +0.j 4. +0.j]
 [1. +0.j 2. +0.j 3.5+0.j 5. +0.j]]
complex128


In [26]:
# find the range in numpy
print(np.arange(10,30,10))
print(np.arange(10,30,5))
print(np.arange(10,30,1))

[10 20]
[10 15 20 25]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [27]:
np.linspace(0, 2, 9)  

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [32]:
arr1 = np.array([1,2,3])
arr2 = np.array([2,3,4])

arr1 + arr2

array([3, 5, 7])

In [35]:
# Dimention
arr1 = np.array([[1,2,3],[4,5,6]])
arr1.ndim

2

In [37]:
# Shape
arr1.shape

(2, 3)